name: Build debian package on push or release-tags or pull request.

on:
  push:
    branches:
      - master
    tags:
      - v*

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        include:
          - os: ubuntu-18.04
            codename: bionic
          - os: ubuntu-20.04
            codename: focal
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install debhelper dh-make, and dependent packages for building imagemagick
        shell: bash
        run: |
          sudo apt install -y debhelper dh-make dpkg-dev \
               libfftw3-dev libpng-dev libjpeg-dev libtiff-dev libbz2-dev libdjvulibre-dev libfontconfig1-dev libfreetype6-dev \
               liblcms2-dev liblqr-1-0-dev liblzma-dev libpango1.0-dev libopenexr-dev libwmf-dev zlib1g-dev libxml2-dev libgif-dev libwmf-dev libperl-dev

      - name: Build debian package
        shell: bash
        run: |
          bash scripts/all.sh

      - name: Get debian package name
        shell: bash
        run: |
          echo "::set-output name=filename::$(basename $(find . -type f -name \*.deb))"
        id: get_deb_name

      - name: Upload result
        uses: actions/upload-artifact@v1
        with:
          name: ${{ matrix.codename }}
          path: imagemagick/${{ steps.get_deb_name.outputs.filename }}

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  upload:
    needs: release
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        codename: [bionic, focal]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.codename }}
          path: artifact

      - name: Get debian package name
        shell: bash
        run: |
          echo "::set-output name=filename::$(find artifact/ -type f -name \*.deb)"
        id: get_deb_name

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: artifact/${{ steps.get_deb_name.outputs.filename }}
          asset_name: ${{ steps.get_deb_name.outputs.filename }}
          asset_content_type: application/vnd.debian.binary-package
